name: Scan the source code
on: [push]

jobs:
  Flawfinder-job:
  steps:
    -name: flawfinder_scan
     uses: david-a-wheeler/flawfinder@2.0.19
     with:
       arguments: '--sarif ./'
       output: 'flawfinder_results.sarif'
            
